### PR TITLE
Add Windows 11 and Server 2022 support

### PR DESCRIPTION
**Pull request by mwbowers**

### CODE REVIEW

**Comment by mwbowers** [comment]
Didn't see #14 till just now.  Merge if you'd like.  Thanks for the tool.

**Comment by pruggit** [comment]
Thank you for your valuable input. The current implementation of the Windows version detection aligns with the official method from Microsoft. Please refer to the following document for further information: [Windows detection rules](https://github.com/pruggitorg/detect-windows-version/blob/master/docs/windows-version-detection-rules.md)

The current method `public static OperatingSystem GetOperatingSystem()` should stick with the Microsoft's detection rules. Yet, a new enumeration will be introduced, since there is a design flaw in the naming of the enumeration.
The current enumeration will be set to obsolet. This allows developers to switch to the new enumeration `enum WindowsPlatform` when they are ready.

Future improvements will add the capability to determine (with an additional method) the Windows product. This will make it possible to detect, e.g., whether it is Windows 11 or Windows 10 (while it is the same Windows platform having version 10.0)
As suggested by you, this will be achieved by additionally querying the build number.

**Comment by sgf** [comment]
Windows 11 has been around for a long time, and maybe we shouldn't keep the detections pending for that system.

**Comment by pruggit** [comment]
@mwbowers Thanks for your update and sorry it took so long to merge. I think it is not necessary, contrary to my original opinion, that both the Windows platform (e.g. Windows10orHigher for Windows 10 and 11) and the Windows product have to be identified.
The main purpose of this extension is to detect if it is, for example, Windows 10 or Windows 11, even though they are technically the same platform.
If someone is interested in this platform information anyway, he or she can query MajorVersion.

**Pull request merged**
