### PR TITLE
Updated to NET8

### PR DESCRIPTION
**Pull request by xafero**
The project now runs under .NET Framework 4.6.2 still - but also under .NET (Core) 8.0 now.

### CODE REVIEW

**Comment by afuersch** [comment]
@pruggit Can you review this PR please?
I would need a NET Core version of this library :)

**Comment by peterder72** [comment]
+1. Small change, but big enabler for most @pruggit

**Comment by afuersch** [comment]
As a workaround or permanent solution I removed the dependency to this library and instead use 
- .NET8 built-in functionality
- `System.Management` package, see https://stackoverflow.com/questions/75367335/c-sharp-determine-os-version-in-net-6

# Example code

```csharp
    public static void Main()
    {
        var os = Environment.OSVersion;
        Console.WriteLine("Current OS Information:\n");
        Console.WriteLine("Version: {0}", os.Version.ToString(4));
        Console.WriteLine("Version String: {0}", os.VersionString);
        Console.WriteLine("Description: '{0}'", RuntimeInformation.OSDescription);
        Console.WriteLine("Friendly name: '{0}'", GetOSFriendlyName());
        Console.WriteLine("64bit: '{0}'", Environment.Is64BitOperatingSystem);
    }

    public static string GetOSFriendlyName()
    {
        string result = string.Empty;
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            ManagementObjectSearcher searcher = new("SELECT Caption FROM Win32_OperatingSystem");
            ManagementObject os = searcher.Get().Cast<ManagementObject>().First();
            if (os["Caption"].ToString() is string osResult)
            {
                result = osResult;
            }
        }
        else
        {
            return RuntimeInformation.OSDescription;
        }

        return string.IsNullOrWhiteSpace(result) ? RuntimeInformation.OSDescription : result;
    }
```

# Output

```
Current OS Information:

Version: 10.0.22631.0
Version String: Microsoft Windows NT 10.0.22631.0
Description: 'Microsoft Windows 10.0.22631'
Friendly name: 'Microsoft Windows 11 Pro'
64bit: 'True'
```

This works for my requirements quite good.

Hope this helps someone until this PR is merged :)

**Comment by xafero** [comment]
Another option, use: dotnet add package OSVersionExt.NetStd

**Comment by pruggit** [comment]
@xafero thank you for your great work (and sorry for my late reply)

**Comment by peterder72** [comment]
Thank you @pruggit ! Do you also plan on publishing a Nuget release of the new version?

**Pull request merged**
